## Numpy

#### Neden İhtiyacımız Var?

Pythonda hazır olarak sunulmuş olan liste yapısından daha efektif olarak çalışır; hem daha hızlı çalışır hem de daha az bellek gereksinimi vardır. Veri analizi işlemlerindeki matematiksel hesaplamalar için kullanılıyor.

### Numpy Array'i Nasıl Tanımlanır?

1. Direkt liste tanımlar gibi tanımlayabiliriz.
2. zeros() fonksiyonu ile tüm elemanları 0 olan dizi tanımlayabiliriz. 
3. ones() fonksiyonu ile tüm elemanları 1 olan dizi tanımlayabiliriz.
4. full() fonksiyonu ile tüm elemanları aynı olan dizi tanımlayabiliriz.
5. arange() fonksiyonu ile belirli aralıkta, sabit artış ile dizi tanımlayabiliriz.
6. linspace() fonksiyonu ile belirli aralıkta, eleman sayısına göre sabit bir artış ile dizi tanımlayabiliriz.
7. randint() fonksiyonu ile belirli aralıkta rastgele eleman üreterek dizi tanımlayabiliriz.

In [1]:
import numpy as np

npArrayList=np.array([1,2,3,4,5])
print(type(npArrayList))
print(npArrayList)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [6]:
npZeroArray=np.zeros(5,dtype="int")
print(type(npZeroArray))
print(npZeroArray)

<class 'numpy.ndarray'>
[0 0 0 0 0]


In [8]:
npZeroArray2D=np.zeros((5,5),dtype="int")
print(type(npZeroArray2D))
print(npZeroArray2D)

<class 'numpy.ndarray'>
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [9]:
npOnesArray=np.ones(5,dtype="int")
print(type(npOnesArray))
print(npOnesArray)

<class 'numpy.ndarray'>
[1 1 1 1 1]


In [10]:
npOnesArray2D=np.ones((5,5),dtype="int")
print(type(npOnesArray2D))
print(npOnesArray2D)

<class 'numpy.ndarray'>
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [11]:
npFullArray=np.full((5,5),5)
print(type(npFullArray))
print(npFullArray)

<class 'numpy.ndarray'>
[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [14]:
npArangeArray=np.arange(0,50,5)
print(type(npArangeArray))
print(npArangeArray)

<class 'numpy.ndarray'>
[ 0  5 10 15 20 25 30 35 40 45]


In [15]:
npLinSpaceArray=np.linspace(0,50,10)
print(type(npLinSpaceArray))
print(npLinSpaceArray)

<class 'numpy.ndarray'>
[ 0.          5.55555556 11.11111111 16.66666667 22.22222222 27.77777778
 33.33333333 38.88888889 44.44444444 50.        ]


In [19]:
npRandomArray=np.random.randint(0,50,(5,5))
print(type(npRandomArray))
print(npRandomArray)

<class 'numpy.ndarray'>
[[26 45 49  5 15]
 [46  2 45  6 31]
 [46 29 34 28 48]
 [44  6 30  1 46]
 [36 34 22 34 37]]


### Numpy Array Bilgileri
1. dtype: Arraydeki elemanların veri tipi
2. size: Arraydeki toplam eleman sayısı
3. ndim: Arrayin boyut sayısı
4. shape: Arrayin satır-sütun biilgisi

In [31]:
npArray=np.array([1,2,3,4,5])
print(npArray)
print(npArray.dtype)
print(npArray.size)
print(npArray.ndim)
print(npArray.shape)

[1 2 3 4 5]
int32
5
1
(5,)


In [37]:
npArray2D=np.random.randint(0,50,(5,5))
print(npArray2D)
print(npArray2D.dtype)
print(npArray2D.size)
print(npArray2D.ndim)
print(npArray2D.shape)

[[14  9 49  0  0]
 [33 12 23 11 42]
 [37 12 43 23 13]
 [48 25 46  4 12]
 [36 38 43 45 36]]
int32
25
2
(5, 5)


### Array Elemanlarına Erişmek

1. Index yardımıyla elemanlara erişmek
2. Parçalama yardımıyla eleman alt kümelerine erişmek

##### Index Yardımıyla Elemanlara Erişmek

In [40]:
npArray

array([1, 2, 3, 4, 5])

In [43]:
npArray[0]

1

In [48]:
npArray[-1]

5

In [49]:
npArray[0]=0
npArray

array([0, 2, 3, 4, 5])

In [50]:
npArray2D

array([[14,  9, 49,  0,  0],
       [33, 12, 23, 11, 42],
       [37, 12, 43, 23, 13],
       [48, 25, 46,  4, 12],
       [36, 38, 43, 45, 36]])

In [59]:
npArray2D[0][0]

14

In [60]:
npArray2D[4][3]=43

In [61]:
npArray2D

array([[14,  9, 49,  0,  0],
       [33, 12, 23, 11, 42],
       [37, 12, 43, 23, 13],
       [48, 25, 46,  4, 12],
       [36, 38, 43, 43, 36]])

##### Parçalama yardımıyla eleman alt kümelerine erişmek

array_ismi[baslangic_indeks:bitis_indeks:indeks_artis_miktari]

In [62]:
nparray=np.arange(0,50)
nparray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [66]:
nparray[::]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [67]:
nparray[::5]

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [68]:
nparray[:15:5]

array([ 0,  5, 10])

In [69]:
nparray[15::5]

array([15, 20, 25, 30, 35, 40, 45])

In [70]:
npArray2D

array([[14,  9, 49,  0,  0],
       [33, 12, 23, 11, 42],
       [37, 12, 43, 23, 13],
       [48, 25, 46,  4, 12],
       [36, 38, 43, 43, 36]])

In [71]:
npArray2D[0::2,::]

array([[14,  9, 49,  0,  0],
       [37, 12, 43, 23, 13],
       [36, 38, 43, 43, 36]])

In [72]:
npArray2D[::,0::2]

array([[14, 49,  0],
       [33, 23, 42],
       [37, 43, 13],
       [48, 46, 12],
       [36, 43, 36]])

In [73]:
npArray2D[1::2,1::2]

array([[12, 11],
       [25,  4]])

npArray2D[satir_baslangic_indeks:satir_bitis_indeks:satir_indeks_artis,sutun_baslangic_indeks:sutun_bitis_indeks:sutun_indeks_artis]

### Hazır Fonksiyonlar
1. reshape(): Numpy Array'i yeniden boyutlandırmak için kullanılır.
2. concatenate(): Numpy Arrayleri birleştirmek için kullanılır.
3. split(): Numpy Array'i bölmek-ayırmak için kullanılır.
4. sort(): Numpy Array'i sıralamak için kullanılır.

In [120]:
nparray=np.arange(1,10)
nparray

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [122]:
nparray2D=nparray.reshape((3,3))
nparray2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [125]:
a=np.arange(0,10)
b=np.arange(10,20)
c=np.concatenate([a,b])
print(a)
print(b)
print(c)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [132]:
a=np.array([[1,2,3,4,5],[1,2,3,4,5]])
b=np.array([[6,7,8,9,10],[6,7,8,9,10]])
c=np.concatenate([a,b])#default axis=0, alt alta ekleme yapar.
d=np.concatenate([a,b],axis=1)#axis=1 yan yana ekleme yapar
print(c)
print(d)

[[ 1  2  3  4  5]
 [ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 6  7  8  9 10]]
[[ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]]


In [134]:
nparray=np.arange(1,10)
a,b,c=np.split(nparray,3)
print(a)
print(b)
print(c)

[1 2 3]
[4 5 6]
[7 8 9]


In [140]:
npArray2D=np.random.randint(0,50,(4,4))
npArray2D

array([[13, 31,  8, 31],
       [11, 26, 41, 44],
       [25, 43, 42, 41],
       [11,  1, 17, 38]])

In [145]:
a,b=np.vsplit(npArray2D,[3])
print(a)
print(b)

[[13 31  8 31]
 [11 26 41 44]
 [25 43 42 41]]
[[11  1 17 38]]


In [148]:
c,d=np.hsplit(npArray2D,[3])
print(c)
print(d)

[[13 31  8]
 [11 26 41]
 [25 43 42]
 [11  1 17]]
[[31]
 [44]
 [41]
 [38]]


In [151]:
randomarray=np.random.randint(0,50,(1,10))
print(randomarray)
sortedArray=np.sort(randomarray)
print(sortedArray)

[[39 32 46 15 25 19 12 13 29 26]]
[[12 13 15 19 25 26 29 32 39 46]]


In [159]:
randomArray2D=np.random.randint(0,50,(5,10))
print(randomArray2D)
sortedArray2D=np.sort(randomArray2D,axis=0)#axis=0 ise sütuna göre sırala
sortedArray2DEkstra=np.sort(randomArray2D)#default axis=1 ise satıra göre sırala

[[27  1 43  2 13 28  1 31 27  9]
 [13 15 48 28 28 24 32 34 31 35]
 [49  9  5 41 44 16 45 34 28 31]
 [ 0 17 43 28  1  3 13  1 45 10]
 [49 35  4 26 32 22  7  7 16 41]]


In [157]:
print(sortedArray2D)

[[ 1  2 10 17  8  3  4  9 11  7]
 [ 7  7 27 19 17 26  6 10 14  7]
 [19 32 43 21 25 29 22 13 35 19]
 [30 40 46 29 36 38 30 44 42 45]
 [41 45 48 31 40 49 40 46 47 48]]


In [160]:
print(sortedArray2DEkstra)

[[ 1  1  2  9 13 27 27 28 31 43]
 [13 15 24 28 28 31 32 34 35 48]
 [ 5  9 16 28 31 34 41 44 45 49]
 [ 0  1  1  3 10 13 17 28 43 45]
 [ 4  7  7 16 22 26 32 35 41 49]]


### Matematiksel Fonksiyonlar

1. add(): Tüm elemanlar üzerinde ekleme işlemi yapabildiğimiz fonksiyon.
2. subtract(): Tüm elemanlar üzerinde çıkarma işlemi yapabildiğimiz fonksiyon.
3. multiply(): Tüm elemanlar üzerinde çarpma işlemi yapabildiğimiz fonksiyon.
4. divide(): Tüm elemanlar üzerinde bölme işlemi yapabildiğimiz fonksiyon.
5. power(): Tüm elemanlar üzerinde üs alma işlemi yapabildiğimiz fonksiyon.
6. mod(): Tüm elemanlar üzerinde mod alma işlemi yapabildiğimiz fonksiyon.
7. mean(): Ortalama hesaplama işlemi yapabildiğimiz fonksiyon.
8. sum(): Toplama işlemi yapabildiğimiz fonksiyon.
9. min(): En küçük elemanı bulabildiğimiz fonksiyon.
10. max(): En büyük elemanı bulabildiğimiz fonksiyon.

In [2]:
nparray=np.arange(1,10)
nparray

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
npArrayAdd=np.add(nparray,5)
npArrayAdd

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
npArraySubtract=np.subtract(nparray,2)
npArraySubtract

array([-1,  0,  1,  2,  3,  4,  5,  6,  7])

In [6]:
npArrayMultiply=np.multiply(nparray,3)
npArrayMultiply

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [7]:
npArrayDivide=np.divide(nparray,5)
npArrayDivide

array([0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8])

In [8]:
npArrayPower=np.power(nparray,2)
npArrayPower

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [10]:
npArrayMod=np.mod(nparray,2)
npArrayMod

array([1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [11]:
nparray.mean()

5.0

In [12]:
nparray.max()

9

In [13]:
nparray.min()

1

In [14]:
nparray.sum()

45

### Operatörlerin Array ile Kullanımı

In [20]:
nparray=np.arange(1,10)
nparray

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
nparray=nparray+5
nparray

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [27]:
nparray=nparray-5
nparray

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
nparray*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [29]:
nparray/2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [30]:
nparray//2

array([0, 1, 1, 2, 2, 3, 3, 4, 4], dtype=int32)

In [31]:
nparray**2

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [32]:
nparray%2

array([1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [33]:
nparray[nparray>5]

array([6, 7, 8, 9])

In [34]:
nparray[nparray<5]

array([1, 2, 3, 4])

In [35]:
nparray[nparray==5]

array([5])